services:
  - type: web
    name: ucuzbilet-online
    runtime: docker
    plan: free
    repo: https://github.com/alid67-git/ucuzbilet.online
    branch: main
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
